<?php
/**
 * cosmonautexperience.com
 *
 * Website for The Cosmonaut movie.
 *
 * NOTE OF LICENSE
 * Licensed under GNU General Public License version 3.0
 *
 * Copyright (c) 2013 Tecnilógica Soluciones Avanzadas.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Public License v3.0
 * which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/gpl.html
 *
 * Contributors:
 * Tecnilógica Soluciones Avanzadas - initial API and implementation
 *
 * @package   cosmonautexperience
 * @author    Tecnilógica soluciones avanzadas
 * @copyright Copyright (c) 2003 - 2013, Tecnilógica soluciones avanzadas, S.A. (http://tecnilogica.com/)
 * @license   http://www.gnu.org/licenses/gpl-3.0.html
 * @link      http://cosmonautexperience.com
 *
 *
 *
 * Dictionary messages in English.
 *
 */

return array (

  /** DB */
  "dict_db_video_not_found" => "Video not found",

	/** COMMON */
	"dict_com_404_p"                  => "Something went wrong. But the responsible has already been sent to Siberia and the related commitee has been notified about this. If you need to skip the bureaucracy do it at ",
  "dict_com_5000_people"            => "5000 people",
  "dict_com_about"                  => "ABOUT",
	"dict_com_a_film_made_by"         => "A film made by more than",
	"dict_com_accept"                 => "ACCEPT",
	"dict_com_behind_scenes"					=> "BEHIND THE SCENES",
	"dict_com_browse_our_shop"				=> "BROWSE OUR SHOP",
	"dict_com_buy_k_pass"							=> "BUY K-PASS",
  "dict_com_cancel"                 => "Cancel",
  "dict_com_close"                  => "Close",
  "dict_com_close_session"          => "Close session",
	"dict_com_coming"           			=> "Coming soon",
  "dict_com_cosmonaut_book"         => "The Book",
	"dict_com_creative_commons_p"			=> "The project uses a license which goes beyond the concept of copyright. This allows for infinite new lines of business, and it furthers the scope of distribution in massive numbers.",
	"dict_com_crowdfunding_p"					=> "The Cosmonaut has been one of the most successful projects in the world in the use of crowdfunding, having raised more than €400.000 and becoming a project with more than 4,500 producers.",
	"dict_com_disruptive_team_p"			=> "The Riot Cinema team, amongst the youngest in the Spanish film industry, have been working for over four years to take this film to all your screens.",
  "dict_com_download"               => "DOWNLOAD",
  "dict_com_eastern_eggs"           => "Eastern eggs",
	"dict_com_film_universe"					=> "FILM UNIVERSE",
	"dict_com_facebook"								=> "Facebook",
	"dict_com_foo_about"							=> "About",
  "dict_com_foo_blog"               => "Blog",
	"dict_com_foo_contact"						=> "Contact",
	"dict_com_foo_behind"						  => "Behind the scenes",
	"dict_com_foo_demand"							=> "Demand a show",
  "dict_com_foo_downloads"          => "Downloads",
	"dict_com_foo_find"								=> "Find a premiere",
	"dict_com_foo_film_universe"			=> "Film universe",
  "dict_com_foo_go_to_the_web_in"   => "Ir a la web en español",
  "dict_com_foo_its_special"        => "It's special",
	"dict_com_foo_k_program"					=> "K-Program",
	"dict_com_foo_nayik"              => "Nayik",
	"dict_com_foo_newsletter"					=> "Newsletter",
	"dict_com_foo_organize"						=> "Organize a premiere",
	"dict_com_foo_panorama"						=> "Panorama",
	"dict_com_foo_plan"								=> "The Plan",
	"dict_com_foo_press"							=> "Press",
	"dict_com_foo_scripts"						=> "Scripts",
	"dict_com_foo_shop"								=> "Shop",
	"dict_com_foo_team"								=> "The team",
	"dict_com_foo_the_experience"			=> "LIVE EXPERIENCE",
	"dict_com_foo_the_film"						=> "THE FILM",
  "dict_com_foo_the_project"        => "The project",
	"dict_com_foo_timeline"						=> "Timeline",
  "dict_com_foo_trailer"            => "Trailer",
  "dict_com_foo_trailer_and_web"    => "The trailer and the website are licensed under Creative Commons Attribution Share Like Non Commercial 3.0 Unported",
	"dict_com_foo_transmedia"					=> "Transmedia",
	"dict_com_foo_remix"							=> "REMIX",
	"dict_com_foo_riot"								=> "The Cosmonaut is a project by Riot Cinema Collective",
	"dict_com_foo_submit"							=> "Submit you creation",
	"dict_com_foo_submissions"				=> "View submissions",
	"dict_com_foo_watch_it"						=> "Watch it now",
  "dict_com_foo_website_2012"       => "Website 2012",
  "dict_com_foo_with_collaboration" => "WITH THE COLLABORATION OF",
  "dict_com_hummingbird_series"     => "The Hummingbird",
  "dict_com_k_pass"                 => "K-PASS",
	"dict_com_latest_blog"						=> "Latest from the blog",
	"dict_com_licenses"     					=> "LICENSES",
	"dict_com_live_experience"				=> "LIVE EXPERIENCE",
  "dict_com_materials"              => "MATERIALS",
  "dict_com_nayik"									=> "Nayik",
  "dict_com_ope_error"              => "There was an error performing the operation",
  "dict_com_ope_success"            => "Operation successfully completed",
	"dict_com_read_more"							=> "Read more",
  "dict_com_secret_newsletter"      => "Our secret newsletter",
  "dict_com_sign_in"                => "SIGN IN",
	"dict_com_shop"    	              => "SHOP",
  "dict_com_the_book"               => "The Book",
  "dict_com_the_cosmonaut"          => "The Cosmonaut",
  "dict_com_thecosmonaut"           => "thecosmonaut",
  "dict_com_timeline"               => "TIMELINE",
  "dict_com_title"                  => "The Cosmonaut",
  "dict_com_terms_of_service"     	=> "TERMS OF SERVICE",
  "dict_com_transmedia_episodes"    => "Transmedia episodes",
  "dict_com_twitter"								=> "Twitter",
  "dict_com_your_account"           => "Your account",

	/** ABOUT */
	"dict_abo_4_years_working"				=> "4 years working in a beautiful project",
	"dict_abo_behind_scenes"					=> "Behind the scenes",
	"dict_abo_behind_p1"							=> "The Cosmonaut, like epic romances, has been a looooong and hard journey full of valuable lessons.",
	"dict_abo_behind_p2"							=> "Time travel with us from the first conversation about cosmonauts to the film premiere four years later!",
	"dict_abo_disruptive_team"				=> "BY A DISRUPTIVE TEAM",
	"dict_abo_download_photo"					=> "Download film stills",
	"dict_abo_download_plan"					=> "Download The Plan",
	"dict_abo_download_press"					=> "Download complete Press Kit",
	"dict_abo_for_journalist"					=> "Journalists, bloggers and media, here’s all you need to know about the project. Some pictures as well. And everything under a Creative Commons licence, so you can use them wherever you want.",
	"dict_abo_impossible"       			=> "The impossible idea",
	"dict_abo_impossible_p1"       		=> "Some time ago we wanted to make a movie, and on the way, reinvent how films were financed, produced and distributed. Search our own path and engage the audience.",
	"dict_abo_impossible_p2"       		=> "They said that we were crazy. That it was impossible. That it was not realistic and that would never work.",
	"dict_abo_impossible_p3"       		=> "Do didn't believe them.",
	"dict_abo_learn_more"							=> "Watch video",
	"dict_abo_meet_all_the_people"		=> "MEET ALL THE PEOPLE INVOLVED",
	"dict_abo_more_than_4500"					=> "MORE THAN 4.500 BACKERS",
	"dict_abo_meet_the_team"					=> "Meet the team",
	"dict_abo_meet_the_team_p"				=> "The Riot Cinema crew and all the other people that has been involved in the project",
  "dict_abo_or_check_our_special"   => "or check our special thanks blogpost",
	"dict_abo_press_area"							=> "Press area",
	"dict_abo_team_bruno_1"						=> "Second unit Director",
  "dict_abo_team_bruno_2"           => "Executive producer",
	"dict_abo_team_carola"						=> "Executive producer",
	"dict_abo_team_nico_1"						=> "Director - Executive producer",
  "dict_abo_team_nico_2"            => "Screenwriter - Editor",
	"dict_abo_three_principles"				=> "The three principles",
	"dict_abo_timeline"            		=> "Timeline",
	"dict_abo_under_creative_commons"	=> "UNDER CREATIVE COMMONS",
	"dict_abo_with_the_help_of_1"			=> "With the help of hundreds of professionals and the support of more than 4500 backers, ",
	"dict_abo_with_the_help_of_2"			=> "\"The Cosmonaut\" has become a reallity. Learn more about the project",
	"dict_abo_with_the_help_of_3"			=> "and the team behind it.",

  /** BEHIND THE SCENES */
  "dict_beh_bronking_of"			=> "Fighting Of",
  "dict_beh_bronking_of_p"		=> "It is said that the grass never grows on the spot where filmmakers have trod. Coming soon.",
  "dict_beh_eastern_p"        => "Discarded material, outtakes and \"behind the scenes\" gems. Only for cosmonauts with K-Pass.",
  "dict_beh_hummingbird"			=> "The Hummingbird",
  "dict_beh_hummingbird_p1"		=> "Blur the boundaries between reality and fiction.",
  "dict_beh_hummingbird_p2"		=> "Is the legend upon which \"The Cosmonaut\" is based really a legend?",
  "dict_beh_i_hear_voices"    => "I HEAR VOICES FROM SPACE",
  "dict_beh_i_hear_voices_p"  => "In FK Digital Records they dared to put an original soundtrack to the script. You can listen to it on the webisodes.",
  "dict_beh_its_been"         => "It has been an incredible journey.",
  "dict_beh_original"         => "ORIGINAL SOUNDTRACK",
  "dict_beh_original_p"       => "The official soundtrack. With Joan Valent as the main composer.",
  "dict_beh_revive"           => "Relive it with us.",
  "dict_beh_soundtracks"      => "Original soundtracks",
  "dict_beh_transmedia"       => "TRANSMEDIA SESSIONS",
  "dict_beh_transmedia_p"     => "A further 23 incredible tunes. Many of them used in the webisodes or on discarded scenes.",
  "dict_beh_video_diaries"    => "Video-diaries",

	/** CARTO DB */
	"dict_car_all_screenings"     => "VIEW ALL SCREENINGS",
  "dict_car_cartodb_1"         	=> " projections in ",
  "dict_car_cartodb_2"          => " countries.",
  "dict_car_cartodb_3"          => " country.",
  "dict_car_data_city"					=> "City",
  "dict_car_data_date"					=> "Date",
  "dict_car_data_descriptor"		=> "Event",
  "dict_car_data_tickets"				=> "Tickets",
  "dict_car_every_show"					=> "Every show of \"The Cosmonaut\" is different: extra material, Q&A with the team, afterparty ... find the nearest screening, ask for one or organize one yourself.",
  "dict_car_explore"						=> "EXPLORE MAP",
  "dict_car_find_a_projection"	=> "Find a projection or organize it yourself for living the whole Cosmonaut Experience.",
  "dict_car_offline_experience" => "Live the offline experience",

  /** DASHBOARD */
  "dict_das_are_you_sure"           => "Are you sure?",
  "dict_das_delete_account"         => "Delete your account",
  "dict_das_deleted_account"        => "You account has been successfully deleted",
  "dict_das_deleted_account_error"  => "There was a error deleting your account",
  "dict_das_deleting_account"       => "Your account is beign deleted ...",
  "dict_das_err_format_email"       => "Wrong E-Mail format",
  "dict_das_err_required_firstname" => "First name is required",
  "dict_das_err_required_lastname"  => "Last name is required",
  "dict_das_err_required_email"     => "E-Mail is required",
  "dict_das_its_great_to_have_you"  => "It's great to have you around for a while.",
  "dict_das_looks_like_you"         => "Looks like you still have a lot to discover",
  "dict_das_looks_like_you_still"   => "Looks like you still have things to discover",
  "dict_das_looks_like_experienced" => "You are already an experienced cosmonaut!",
  "dict_das_this_will_completely"   => "This will completely remove your user account",
  "dict_das_this_will_update"       => "This will update your user profile",
  "dict_das_save_changes"           => "SAVE CHANGES",
  "dict_das_update_account"         => "Update your account",
  "dict_das_updated_account"        => "You account has been successfully updated",
  "dict_das_updated_account_error"  => "There was a error updating your account",
  "dict_das_updating_account"       => "Your account is beign updated ...",
  "dict_das_welcome_back"           => "Welcome back, Cosmonaut",
  "dict_das_yes_im_sure"            => "YES I'M SURE",
  "dict_das_your_account"           => "Your account data",
  "dict_das_your_email"             => "Your email",
  "dict_das_your_code"              => "Your cosmonaut code",
  "dict_das_your_name"              => "Your name",
  "dict_das_your_surname"           => "Your surname",

  /** EVENTS */
	"dict_eve_browse"			=> "Browse by date",
	"dict_eve_buy"				=> "Buy tickets",
	"dict_eve_city"				=> "CITY",
	"dict_eve_date"				=> "DATE",
	"dict_eve_more"				=> "VIEW MORE",
	"dict_eve_no_tickets"	=> "No tickets",
	"dict_eve_venue"			=> "VENUE",

	/** HOME */
	"dict_hom_32_webisodes"				 => "Webisodes, a book, the Fighting Of, a mockumentary, tons of \"behind the scenes\" videos and exclusive access to our secret newsletter. Buy it for just 5€ or get it for free buying any other item on the shop.",
	"dict_hom_a_film_32_web"			 => "32 additional webisodes, a book and an incredible journey of 4 years working on the project you can now see.",
	"dict_hom_a_film_made_by"			 => "A film made by more than ",
	"dict_hom_countdown_1"         => "ONLINE FOR FREE IN ",
  "dict_hom_countdown_2"         => " DAYS",
  "dict_hom_creative_commons"		 => "CREATIVE COMMONS",
	"dict_hom_crowdfunding"				 => "CROWDFUNDING",
	"dict_hom_disruptive_team"		 => "A DISRUPTIVE TEAM",
	"dict_hom_enjoy_a_new_way"		 => "Enjoy a new way to experience stories and inmerse yourself in the transmedia universe of The Cosmonaut",
	"dict_hom_get_your_k_pass"     => "Buy your K-Pass and get unlimited access to content",
	"dict_hom_how_has_it_be_done"  => "How has it been done",
	"dict_hom_go_to_remix"				 => "GO TO REMIX",
	"dict_hom_learn_about_one"		 => "Learn about one of the most incredible quests on the history of Indie film",
	"dict_hom_more"        				 => "LEARN MORE",
	"dict_hom_much_more_than"			 => "Much more than a film",
	"dict_hom_producers_list"			 => "PRODUCER'S LIST",
	"dict_hom_stats_get_lost_1"		 => "Stas gets lost in space. When he comes back, he finds Earth",
	"dict_hom_stats_get_lost_2"		 => "completely empty. Yulia and Andrei wait for him in a collapsing world.",
	"dict_hom_stats_get_lost_3"		 => "How far would you go for love?",
	"dict_hom_watch_it_for_free"	 => "Watch it free",

  /** K-PASS */
  "dict_kpa_32_webisodes_1"         => "32 web episodes, a book, the Fighting Of, a mockumentary, tons of \"behind the scenes\" videos and exclusive access to our secret newsletter. Buy it for ",
  "dict_kpa_32_webisodes_2"         => "just 5€",
  "dict_kpa_32_webisodes_3"         => "or get it free buying any other item on the shop.",
  "dict_kpa_become_part"            => "Join the k-program",
  "dict_kpa_buy_yours"              => "Buy yours",
  "dict_kpa_buy_your_k_pass"        => "BUY YOUR K-PASS",
  "dict_kpa_or_get_it_for_free"     => "Or get for free with any item in our shop",
  "dict_kpa_still"                  => "Don't have it yet?",
  "dict_kpa_unlock_more_than"       => "Unlock more than 50 exclusive contens",

  /** LOGIN */
  "dict_log_are_you"                => "ARE YOU A COSMONAUT?",
  "dict_log_forgot"                 => "Get my password",
  "dict_log_insert_your"            => "INSERT YOUR K-PASS CREDENTIALS",
  "dict_log_err"                    => "Invalid access data",
  "dict_log_err_format_login"       => "Wrong e-mail format",
  "dict_log_err_required_login"     => "E-mail is required",
  "dict_log_err_required_password"  => "Password is required",
  "dict_log_err_missing"            => "E-mail and password are required",
  "dict_log_sign_in"                => "SIGN IN",
  "dict_log_your_email"             => "Your e-mail",
  "dict_log_your_password"          => "Your password",
  "dict_log_what_is_this"           => "What is this?",

  /** MAIL */
  "dict_mai_header_thankyou"        => "[ CosmonautExperience.com ] Thank you!",
  "dict_mai_header_text_1"          => "Thank you for your donation!",
  "dict_mai_header_text_2"          => "Your account has been created and you can get you password in the following link with your e-mail address: ",

  /** MOVIE */
	"dict_mov_average"								=> "Average donation is ",
	"dict_mov_back_to_website"				=> "Back to cosmonautexperience.com website",
	"dict_mov_enjoying_1"							=> "Enjoying the film? \"The Cosmonaut\" is a",
	"dict_mov_enjoying_2"							=> "four years effort,",
	"dict_mov_enjoying_3"							=> "built by fans and ",
	"dict_mov_enjoying_4"							=> "creator together. Remember you can help us by ...",
	"dict_mov_go_to_beginning"				=> "GO TO BEGINNING",
	"dict_mov_if_you_pay_1"						=> "If you pay more than 5€ you'll get your ",
	"dict_mov_k_pass"									=> "K-Pass",
	"dict_mov_or"											=> "or",
	"dict_mov_or_sharing"							=> "Or sharing the link with your friends.",
	"dict_mov_pay_with_paypal"				=> "Pay with Paypal",
	"dict_mov_paying_what_you_want"		=> "Paying what you want",
	"dict_mov_share"									=> "Share the link and do it for free",
	"dict_mov_share_facebook"					=> "SHARE ON FACEBOOK",
	"dict_mov_share_twitter"					=> "SHARE ON TWITTER",
	"dict_mov_the_cosmonaut"					=> "THE COSMONAUT",
	"dict_mov_watch_movie"						=> "WATCH THE MOVIE",
	"dict_mov_watch_the_movie"				=> "Watch the movie and pay what you want",
	"dict_mov_we_believe"							=> "We believe in a friendly relationship between creators and fans.",
	"dict_mov_we_can_only_1"					=> "We can only make films with your help, but ",
	"dict_mov_we_can_only_2"					=> "we want you to choose",

	/** NAYIK */
  "dict_nay_ago_1"                  => "",
  "dict_nay_ago_2"                  => "",
  "dict_nay_ago_3"                  => "DAYS AGO",
  "dict_nay_says"                   => "says",
	"dict_nay_story_alive"						=> "History is alive and is in Nayik.",

  /** REMIX */
  "dict_rem_a_film_by"              => "A film by",
  "dict_rem_attribution"            => "ATRIBUTION",
  "dict_rem_attribution_p1"         => "Don’t distribute the content of",
  "dict_rem_attribution_p2"         => "\"The Cosmonaut\" without giving us credit ",
  "dict_rem_attribution_p3"         => "as author.",
  "dict_rem_attribution_p4"         => "Here we explain ",
  "dict_rem_attribution_p5"         => "how to do it.",
  "dict_rem_commercial"             => "NON COMMERCIAL",
  "dict_rem_commercial_p1"          => "Commercial use is",
  "dict_rem_commercial_p2"          => "prohibited without",
  "dict_rem_commercial_p3"          => "our prior consent.",
  "dict_rem_derivatives"            => "NO DERIVATIVES",
  "dict_rem_derivatives_p1"         => "Some materials can’t be altered or generate ",
  "dict_rem_derivatives_p2"         => "new pieces with them. We will",
  "dict_rem_derivatives_p3"         => "indicate which with the following symbol",
  "dict_rem_download_adapt"         => "Download our website’s",
  "dict_rem_download_adapt_2"       => "code for your project",
  "dict_rem_download_direct"        => "Direct download",
  "dict_rem_download_direct_2"      => "separate clips",
  "dict_rem_download_guide"         => "Material guide",
  "dict_rem_download_guide_2"       => "essential",
  "dict_rem_download_materials"     => "Download the film material (coming soon)",
  "dict_rem_download_torrent"       => "Download the .torrent file",
  "dict_rem_download_torrent_2"     => "all the clips",
  "dict_rem_exceptions"             => "few exceptions",
  "dict_rem_help_of"                => "This section wouldn’t have been possible without the priceless help of ...",
  "dict_rem_license"                => "KEEP THE SAME LICENSE",
  "dict_rem_license_p1"             => "If you alter or transform the piece, or",
  "dict_rem_license_p2"             => "if you generate a derived piece, you ",
  "dict_rem_license_p3"             => "can only distribute it under ",
  "dict_rem_license_p4"             => "the same license as the original.",
  "dict_rem_other_conditions"       => "These are some other conditions you might find",
  "dict_rem_permissions"            => "ADDITIONAL PERMISSIONS",
  "dict_rem_permissions_p1"         => "If you see this icon the license",
  "dict_rem_permissions_p2"         => "is not applicable to the content as a whole.",
  "dict_rem_permissions_p3"         => "Use the ",
  "dict_rem_permissions_p4"         => "License Guide.",
  "dict_rem_remix"                  => "REMIX",
  "dict_rem_remix_p1"               => "You can alter, create new ",
  "dict_rem_remix_p2"               => "versions or use it on ",
  "dict_rem_remix_p3"               => "your own pieces.",
  "dict_rem_remix_movie"            => "Copy. Share. Remix",
  "dict_rem_remix_the_way"          => "Our film is licensed under Creative Commons. You can distribute it for free so long as you don’t make money out of it, directly or indirectly. You can also remix it however you want, or choose different takes than those used by the editors. Or use our HD images of cosmonauts, landscapes and desolate areas in your personal project. The concept is simple: if you don’t win, neither do we. If you obtain some benefit, we share it.",
  "dict_rem_share"                  => "SHARE",
  "dict_rem_share_p1"               => "You can share, copy, ",
  "dict_rem_share_p2"               => "distribute and exhibit it.",
  "dict_rem_this_is_what_you"       => "This is what you can do ...",
  "dict_rem_upload"                 => "UPLOAD YOUR VIDEO",
  "dict_rem_upload_p1"              => "Have you created something with our material? Upload it to our Vimeo channel and",
  "dict_rem_upload_p2"              => "share it with the community!",
  "dict_rem_week_remix_1"           => "THE WEEKS REMIX IN ",
  "dict_rem_week_remix_2"           => "\"THE COSMONAUT REMIX\"",
  "dict_rem_what_you_respect"       => "This is what you must observe",
  "dict_rem_with_all_content"       => "... with all the content of \"The Cosmonaut\" (except ",

  /** THANKS */
  "dict_tha_account"                => "YOUR ACCOUNT HAS BEEN CREATED.",
  "dict_tha_p1"                     => "You can request you K-Pass password",
  "dict_tha_p2"                     => "or",
  "dict_tha_p3"                     => "start watching the movie now.",
  "dict_tha_request_password"       => "GET PASSWORD",
  "dict_tha_thank_you"              => "THANK YOU!",
  "dict_tha_watch_it_now"           => "WATCH IT NOW",

  /** TIMELINE */
  "dict_tim_2008end_p"              => "We make the short-film \"The Cosmonaut’s journey\" into a full feature film \"The Cosmonaut\".",
  "dict_tim_2008end"                => "END OF 2008",
  "dict_tim_2009begin_p"            => "The reading of \"Poetry for Cosmonauts\" gives the future film a final shape.",
  "dict_tim_2009begin"              => "BEGINNING OF 2009",
  "dict_tim_20090118"               => "18, JAN, 2009",
  "dict_tim_20090118_p"             => "We manage to get two training cosmonaut suits, which will accompany us throughout the adventure, and with which we will shoot the film two years later.",
  "dict_tim_20090124"               => "24, JAN, 2009",
  "dict_tim_20090124_p"             => "We decide to fund \"The Cosmonaut\" through Crowdfunding.",
  "dict_tim_20090216"               => "16, FEB, 2009",
  "dict_tim_20090216_p"             => "We meet Henry Pierrot, the author of \"Poetry for Cosmonauts\", who joins the project.",
  "dict_tim_20090320"               => "20, MAR, 2009",
  "dict_tim_20090320_p"             => "We travel to Star City (Moscow) the impressive location over which we will obsess throughout the project.",
  "dict_tim_20090415"               => "15, APR, 2009",
  "dict_tim_20090415_p"             => "The prestigious Vostok studio supports the project and decides to create our website.",
  "dict_tim_20090422"               => "22, APR, 2009",
  "dict_tim_20090422_p"             => "Laszlo Kovacs creates the logo of the film, the Hummingird.",
  "dict_tim_20090424"               => "24, ABR, 2009",
  "dict_tim_20090424_p"             => "We introduce the project in Medialab (Madrid) and on an improvised auction we get our first producer.",
  "dict_tim_20090511"               => "11, MAY, 2009",
  "dict_tim_20090511_p"             => "We launch the website that allows you to become a producer.",
  "dict_tim_20090623"               => "23, JUN, 2009",
  "dict_tim_20090623_p"             => "Eduard Artemyev, composer of our admired Andrey Tarkovsky, allows us to use the music he composed for \"Solaris\".",
  "dict_tim_20090627"               => "27, JUN, 2009",
  "dict_tim_20090627_p"             => "El País calls us \"the most stimulating project in Spanish cinema\" on a full page article of their weekend supplement.",
  "dict_tim_20090630"               => "30, JUN, 2009",
  "dict_tim_20090630_p"             => "Festival \"Cosmonauts\": Famous indie bands play in benefit of the film.",
  "dict_tim_20090712"               => "12, JUL, 2009",
  "dict_tim_20090712_p"             => "Our first investor.",
  "dict_tim_20090820"               => "20, AUG, 2009",
  "dict_tim_20090820_p"             => "In 10 minutes we finance the second print of \"Poetry for Cosmonauts\", the book that is part of the origins of the film.",
  "dict_tim_20091014"               => "14, OCT, 2009",
  "dict_tim_20091014_p"             => "We attend Power to The Pixel in the UK. The idea of transmedia profoundly transforms us.",
  "dict_tim_20091015"               => "15, OCT, 2009",
  "dict_tim_20091015_p"             => "We reach 1000 producers. We make a party to celebrate it. We can’t fit in the venue.",
  "dict_tim_20100121"               => "21, JAN, 2010",
  "dict_tim_20100121_p"             => "Teaser of the film. An immediate success. Stas (by then still \"Stan\") is our great friend and incredible actor Carlos Martínez Abarca.",
  "dict_tim_20100211"               => "11, FEB, 2010",
  "dict_tim_20100211_p"             => "Nicolás writes the script. We decide, after careful consideration, to do the film in English.",
  "dict_tim_20100407"               => "7, APR, 2010",
  "dict_tim_20100407_p"             => "WIRED mentions us as \"one of the greatest successes of collective creativity\".",
  "dict_tim_20100503"               => "3, MAY, 2010",
  "dict_tim_20100503_p"             => "Teaser Remix Experience: over 100 remixes of the Teaser Trailer. Some of them are incredible. It reaffirms us on doing the same thing with the film.",
  "dict_tim_20100602"               => "2, JUN, 2010",
  "dict_tim_20100602_p"             => "We publish our strategy (The Plan), the budget and financial plan and the first copy of the script.",
  "dict_tim_20100620"               => "20, JUN, 2010",
  "dict_tim_20100620_p"             => "Our new web, also done by Vostok. Incredible design.",
  "dict_tim_20101006"               => "6, OCT, 2010",
  "dict_tim_20101006_p"             => "We are chosen by the Latin American Film Training and we travel to Hollywood to learn how it works.",
  "dict_tim_20101123"               => "23, NOV, 2010",
  "dict_tim_20101123_p"             => "Pre-production begins.",
  "dict_tim_20110317"               => "17, MAR, 2011",
  "dict_tim_20110317_p"             => "We publish the second teaser. Still with scenes shot in Madrid.",
  "dict_tim_20110328"               => "28, MAR, 2011",
  "dict_tim_20110328_p"             => "We show the faces of our three main characters. Three faces from British film and theatre will play Andrei, Yulia and Stas.",
  "dict_tim_20110401"               => "1, APR, 2011",
  "dict_tim_20110401_p"             => "We travel to Moscow so as not to miss the first snows. We publish the scenes we shoot. They are very well received.",
  "dict_tim_20110422"               => "22, APR, 2011",
  "dict_tim_20110422_p"             => "3000 producers.",
  "dict_tim_20110505"               => "2, MAY, 2011",
  "dict_tim_20110505_p"             => "A promising Russian co-producer appears.",
  "dict_tim_20110506"               => "6, MAY, 2011",
  "dict_tim_20110506_p"             => "We close some spectacular locations in Latvia while we finish the rehearsals with the actors.",
  "dict_tim_20110525"               => "25, MAY, 2011",
  "dict_tim_20110525_p"             => "Our Russian investor falls through. We launch the Save The Cosmonaut campaign to get at least 40.000€ in one month. We manage 130.000€ in three days.",
  "dict_tim_20110604"               => "4, JUN, 2011",
  "dict_tim_20110604_p"             => "Shooting starts.",
  "dict_tim_20110627"               => "27, JUN, 2011",
  "dict_tim_20110627_p"             => "We stream the shoot live.",
  "dict_tim_20110715"               => "15, JUL, 2011",
  "dict_tim_20110715_p"             => "Principal photography finishes.",
  "dict_tim_20111031"               => "31, OCT, 2011",
  "dict_tim_20111031_p"             => "We introduce The Plan 2, a \"recap\" of our previous strategy.",
  "dict_tim_20111104"               => "4, NOV, 2011",
  "dict_tim_20111104_p"             => "First trailer with scenes from the film.",
  "dict_tim_20120224"               => "24, FEB, 2012",
  "dict_tim_20120224_p"             => "Last stage of editing",
  "dict_tim_20120529"               => "25, MAY, 2012",
  "dict_tim_20120529_p"             => "We finish the editing, almost a year after shooting the film. Three soundtracks. 80 minutes of feature film. 80 minutes of transmedia. Many easter eggs and a documentary.",
  "dict_tim_20120715"               => "15, AUG, 2012",
  "dict_tim_20120715_p"             => "We are joined by Entropy (FX), Pecera Estudio (Sound) and Joan Valent (Original score) thanks to 80.000€ from Pepephone.",
  "dict_tim_20121023"               => "23, OCT, 2012",
  "dict_tim_20121023_p"             => "Two years after reediting it, Poetry for Cosmonauts is sold out.",
  "dict_tim_20121123"               => "23, NOV, 2012",
  "dict_tim_20121123_p"             => "We finally close our final strategy and publish \"The Plan 3\".",
  "dict_tim_20121013"               => "13, OCT, 2012",
  "dict_tim_20121013_p"             => "Vení starts working on the awesome animation for the closing credits.",
  "dict_tim_20130214"               => "14, FEB, 2013",
  "dict_tim_20130214_p"             => "Final trailer is launched, we announce a date for the premiere (May 18th). All three are an outright success.",
  "dict_tim_this_has_been"          => "This has been an amazing travel.",
  "dict_tim_read_more"              => "Read more",
  "dict_tim_revive"                 => "Revive it with us",

	/** TRAILER */
  "dict_tra_32_webisodes"         	=> "32 web episodes, the Fighting Of, an incredible mockumentary, tons of \"behind the scenes\" and our secret newsletter for only 5€ (or free included with any other item in our shop).",
  "dict_tra_also_in_theaters"     	=> "Also in theaters",
  "dict_tra_beyond"               	=> "It goes beyond copyright",
  "dict_tra_check_out"            	=> "Check out the reasons that have made this project something that will change the way we understand the cinema.",
  "dict_tra_cosmonaut_experience" 	=> "\"The Cosmonaut\" experience is much better when you share it with friends. Find the nearest screening, ask for one or organize one yourself.",
  "dict_tra_demand_a_show"        	=> "ASKING FOR A PREMIERE",
  "dict_tra_demand_your_offline"  	=> "Ask us for a premiere in your city and organize it yourself, we will help you.",
  "dict_tra_download_material"    	=> "Copy, remix, and distribute the film as you like.",
  "dict_tra_get_your_k_pass"       	=> "All the experience with your K-Pass",
  "dict_tra_go_to_website"        	=> "See old website",
  "dict_tra_has_been_made"        	=> "The Cosmonaut has been possible thanks to more than 4500 fans and investors.",
  "dict_tra_in_all_your"          	=> "In all your screens",
  "dict_tra_its_an_experience"    	=> "It's an experience",
  "dict_tra_its_crowdfunded"      	=> "It's crowdfunded",
  "dict_tra_its_free"             	=> "It's free",
  "dict_tra_or"                   	=> "or",
  "dict_tra_organize_it"          	=> "ORGANIZING IT",
  "dict_tra_planned_shows"        	=> "Planned shows",
  "dict_tra_premiere"             	=> "May 14th 2013",
  "dict_tra_cosmonaut_experience" 	=> "\"The Cosmonaut\" experience is much better when you share it with friends. Find the nearest screening, ask for one or organize one yourself.",
  "dict_tra_theater_experience"  		=> "Cinema experience",
  "dict_tra_this_is_not"          	=> "It's not just a movie: 32 additional episodes, a cinematic experience and much more.",
  "dict_tra_tugg"										=> "Tugg projections",
  "dict_tra_users_demanding"      	=> "Users demanding",
  "dict_tra_watch_it_for_free"    	=> "You can watch it for free or pay for your K-Pass, which gives you access to the whole experience.",
  "dict_tra_watch_the_trailer"    	=> "Watch the trailer",
  "dict_tra_we_have_a_plan"       	=> "We have a plan",
  "dict_tra_we_love_transpar_1"   	=> "We like to be transparent. Download ",
  "dict_tra_we_love_transpar_2"   	=> "here",
  "dict_tra_we_love_transpar_3"   	=> "our whole strategy.",
  "dict_tra_why_you_should"       	=> "Why you cannot miss it",

  /** TRAILER DEMAND EVENT */
  "dict_tra_dem_accept_tos"           => "I have read and accepted the ",
  "dict_tra_dem_alert_me"             => "Alert me only when new events on my area",
  "dict_tra_dem_by_doing_this"        => "By doing this, the organization could give you some merchandising or some free tickets.",
  "dict_tra_dem_cant_find"            => "Can't find anything around you?",
  "dict_tra_dem_close"                => "Close",
  "dict_tra_dem_conf_demand_head"     => "WE HAVE RECORDED YOUR DEMAND",
  "dict_tra_dem_conf_demand_p1"       => "It will appear in the map in the next few hours.",
  "dict_tra_dem_conf_demand_p2"       => "Thank you!",
  "dict_tra_dem_contact_info"         => "Contact info",
  "dict_tra_dem_demand_an_event"      => "Demand an event",
  "dict_tra_dem_error_accept"         => "You should accept the Terms of Service",
  "dict_tra_dem_error_city"           => "Ops, city name is required",
  "dict_tra_dem_error_email"          => "Ops, this email doesn't looks right",
  "dict_tra_dem_error_generic_demand" => "This data helps event organizers a lot",
  "dict_tra_dem_error_locating_head"  => "Ops, there was a problem locating your request",
  "dict_tra_dem_error_locating_body"  => "Something went wrong and we could not locate your request in the map. Please, try it again or contact webmaster if problem persists.",
  "dict_tra_dem_error_sendmail"       => "Ops, it seems that form could not be sent",
  "dict_tra_dem_error_type"           => "Ops, at least one type is required",
  "dict_tra_dem_error_zip_code"       => "Ops, zip code is required",
  "dict_tra_dem_experience"           => "Experience",
  "dict_tra_dem_home_screening"       => "Home screening",
  "dict_tra_dem_normal"               => "Normal",
  "dict_tra_dem_postal_code"          => "Postal code",
  "dict_tra_dem_prefered_event"       => "Prefered event",
  "dict_tra_dem_really"               => "Really?",
  "dict_tra_dem_submit_proposal"      => "Submit proposal",
  "dict_tra_dem_terms_of_service"     => "Terms of service",
  "dict_tra_dem_type"                 => "Type",
  "dict_tra_dem_yes_im_up"            => "Yes I'm up to help someone to organize an event.",
  "dict_tra_dem_you_can_select"       => "You can select as many as you want. This will give the organizer an idea of the event you want.",
  "dict_tra_dem_your_city"            => "Your city",
  "dict_tra_dem_your_email"           => "Your email",
  "dict_tra_dem_wanna_help"           => "Wanna help?",

  /** TRAILER / ORGANIZE */
  "dict_tra_org_35mm"                 => "35mm",
  "dict_tra_org_about_you"            => "ABOUT YOU",
  "dict_tra_org_additional_contents"  => "Additional Contents",
  "dict_tra_org_address"              => "City of the event",
  "dict_tra_org_after_party"          => "After party",
  "dict_tra_org_amateur_event"        => "SemiPro/Amateur event",
  "dict_tra_org_complete_name"        => "Complete Name",
  "dict_tra_org_conf_organize_head"   => "Thanks",
  "dict_tra_org_conf_organize_p1"     => "We will contact you as soon as possible in order to close all details about your event. In the next few minutes you will also  receive a summary of your submission.",
  "dict_tra_org_conf_organize_p2"     => "Looking forward to take The Cosmonaut to ",
  "dict_tra_org_date"                 => "Date",
  "dict_tra_org_dcp"                  => "DCP",
  "dict_tra_org_dni"                  => "Valid iD",
  "dict_tra_org_dvd_bluray"           => "DVD",
  "dict_tra_org_describe_your_event"  => "Describe your event",
  "dict_tra_org_detailed_description" => "Detailed description about your venue and your event",
  "dict_tra_org_dont_be_afraid_1"     => "Don't be afraid. We just need some details about your idea.",
  "dict_tra_org_dont_be_afraid_2"     => "Before filling the form we need you to read our ",
  "dict_tra_org_email"                => "Email",
  "dict_tra_org_error_address"        => "Ops, your address is required",
  "dict_tra_org_error_date"           => "Ops, an event date is required",
  "dict_tra_org_error_descriptor"     => "Ops, an event description is required",
  "dict_tra_org_error_email"          => "Ops, this email doesn't looks right",
  "dict_tra_org_error_format"         => "Ops, at least one format is required",
  "dict_tra_org_error_id"             => "Ops, your ID number is required",
  "dict_tra_org_error_generic_org"    => "If you tell us this, we'll be able to help you better",
  "dict_tra_org_error_lang"           => "Ops, at least one language option is required",
  "dict_tra_org_error_name"           => "Ops, your name is required",  
  "dict_tra_org_error_phone"          => "Ops, your phone number is required",
  "dict_tra_org_error_sendmail"       => "Ops, it seems that form could not be sent",
  "dict_tra_org_error_where"          => "Ops, at least one type is required",
  "dict_tra_org_expected_number"      => "Expected number of people",
  "dict_tra_org_extras"               => "EXTRAS",
  "dict_tra_org_final_cost"           => "FINAL COST",
  "dict_tra_org_format"               => "Format",
  "dict_tra_org_free"                 => "FREE",
  "dict_tra_org_language"             => "Language",
  "dict_tra_org_merchandising"        => "MERCHANDISING",
  "dict_tra_org_non_profit"           => "Non-profit",
  "dict_tra_org_organize_your_own"    => "Organize your own real experience",
  "dict_tra_org_phone"                => "Phone",
  "dict_tra_org_professional_event"   => "Professional",
  "dict_tra_org_q_and_a"              => "Q&As",
  "dict_tra_org_screening_guide"      => "Screening guide",
  "dict_tra_org_snacks"               => "Snacks, others",
  "dict_tra_org_streaming"            => "STREAMING",
  "dict_tra_org_submit"               => "Send",
  "dict_tra_org_tdb"                  => "We will talk about money later",
  "dict_tra_org_technical_stuff"      => "TECHNICAL STUFF",
  "dict_tra_org_vo"                   => "V.O.",
  "dict_tra_org_vo_english"           => "V.O. (English subts)",
  "dict_tra_org_vo_spanish"           => "V.O. (Spanish subts)",
  "dict_tra_org_where"                => "Type?",
  "dict_tra_org_your_event"           => "YOUR EVENT",
  "dict_tra_org_your_features"        => "Your features",

  /**TWITTER */ 
  "dict_twitter_hashtag"              => "cosmonautexperience",
	"dict_twitter_text_eastern"					=> "Unveiling the secrets of The Cosmonaut watching it's EasternEggs!",
  "dict_twitter_text_experience"			=> "Mindblown by The Cosmonaut. Watching the webisode ",
  "dict_twitter_text_movie"						=> "Mindblown by The Cosmonaut. Watching it for FREE at ",
  "dict_twitter_text_videodiary"			=> "Watching The Cosmonaut's Videodiaries: making history!",
  
  /** UNIVERSE */
	"dict_uni_18_may"       					=> "Free online May 18",
  "dict_uni_alternate_ending"       => "Alternate ending",
  "dict_uni_coming_1"       				=> "Coming ",
  "dict_uni_coming_2"       				=> "",
  "dict_uni_moon_warm_up"           => "MOON WRAP-UP",
  "dict_uni_moon_warm_up_p"         => "The days before departure, aurora borealis' cover the sky.",
  "dict_uni_star_city_1"            => "Russians never went to",
  "dict_uni_star_city_2"            => "The Moon but... what if they tried",
  "dict_uni_star_city_3"            => "and we never knew about it?",
  "dict_uni_the_beginning"          => "THE BEGINNING",
  "dict_uni_the_beginning_p"        => "In 1957, the first man-made object was put in orbit. That ignited a wild race between two countries that where fighting an undercover war. Earth wasn't enough anymore. The new goal was to conquer the universe.",
  "dict_uni_the_book"               => "The Book",
  "dict_uni_the_cosmonaut"          => "THE COSMONAUT",
  "dict_uni_the_cosmonaut_p"        => "A film that is changing the relationship with spectators. The center piece of the cosmonautic experience.",
  "dict_uni_the_good_old_days"      => "THE GOOD OLD DAYS",
  "dict_uni_the_good_old_days_p"    => "1967. Memories can last until the very last breath. When Stas and Andrei arrived to Star City they met a communications technician named Yulia. She would change their fates forever.",
  "dict_uni_the_journey"            => "THE JOURNEY",
  "dict_uni_the_journey_p"          => "Three days traveling 16.000 Tons of metal 8.000km/h",
  "dict_uni_the_lost_cosmonauts"    => "THE LOST COSMONAUTS",
  "dict_uni_the_lost_cosmonauts_p"  => "The beep sounfs became a rythm. It was a . A heart beep. A few days later, the Soviet Union announced that a spaceship had disintegrated near the atmosphere. An unmanned spaceship of course...",
  "dict_uni_the_moon_files"         => "THE MOON FILES",
  "dict_uni_the_moon_files_p"       => "The voyage draws to an end. In these diaries from the void of space we will see all the pieces of the puzzle fit together. It is the last trip. The Moon Files.",
  "dict_uni_the_true_end"           => "EL VERDADERO FINAL",
  "dict_uni_v_o_i_d"                => "V-O-I-D",
  "dict_uni_v_o_i_d_p_1"            => "Finally, the cosmonaut",
  "dict_uni_v_o_i_d_p_2"            => "comes back to earth",
  "dict_uni_while_nasa"             => "While NASA was what every space agency was meant to be, in the USSR things were very different.",

  /** VIDEO */
  "dict_vid_anonimous"              => "Anonimous",
  "dict_vid_ask"                    => "Pregunta lo que quieras sobre este episodio...",
  "dict_vid_buy_it_for_just"        => "Buy it for just 5€ and unlock everything.",
  "dict_vid_comment"                => "Comment",
  "dict_vid_comment_error"          => "There was a problem posting your comment.",
  "dict_vid_comment_error_logged"   => "You must sign-in to leave a comment.",
  "dict_vid_comment_error_required" => "Comment is required.",
  "dict_vid_comment_success"        => "Comment successfully posted.",
  "dict_vid_get_your_k_pass"        => "Get your K-Pass",
  "dict_vid_more_info"              => "More information",
  "dict_vid_or"                     => "or",
  "dict_vid_questions_about"        => "Questions about this video",
  "dict_vid_sign_in"                => "Sign in",
  "dict_vid_to_comment"             => "to comment",
  "dict_vid_you_need_a_k_pass"      => "You need a k-pass to watch this."
);