<?php
/**
 * cosmonautexperience.com
 *
 * Website for The Cosmonaut movie.
 *
 * NOTE OF LICENSE
 * Licensed under GNU General Public License version 3.0
 *
 * Copyright (c) 2013 Tecnilógica Soluciones Avanzadas.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Public License v3.0
 * which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/gpl.html
 *
 * Contributors:
 * Tecnilógica Soluciones Avanzadas - initial API and implementation
 *
 * @package   cosmonautexperience
 * @author    Tecnilógica soluciones avanzadas
 * @copyright Copyright (c) 2003 - 2013, Tecnilógica soluciones avanzadas, S.A. (http://tecnilogica.com/)
 * @license   http://www.gnu.org/licenses/gpl-3.0.html
 * @link      http://cosmonautexperience.com
 *
 *
 *
 * Dictionary messages in Spanish.
 *
 */

return array (

  /** DB */
  "dict_db_video_not_found"         => "Video no encontrado",

  /** COMMON */
  "dict_com_404_p"                  => "Algo ha ido mal. Pero el responsable ya ha sido deportado a Siberia y el comité pertinente ha recibido una notificación. Si quieres saltarte la burocracia puedes avisarnos en ",
  "dict_com_5000_people"            => "5000 personas",
	"dict_com_about"                  => "EL PROYECTO",
  "dict_com_a_film_made_by"         => "Una película hecha por más de",
  "dict_com_accept"                 => "ACEPTAR",
  "dict_com_behind_scenes"          => "TRAS LAS CÁMARAS",
  "dict_com_browse_our_shop"        => "VISITA LA TIENDA",
  "dict_com_buy_k_pass"             => "COMPRAR EL K-PASS",
  "dict_com_cancel"                 => "Cancelar",
  "dict_com_close"                  => "Cerrar",
  "dict_com_close_session"          => "Cerrar sesión",
  "dict_com_coming"           			=> "Próximamente ...",
  "dict_com_cosmonaut_book"         => "El Libro",
  "dict_com_creative_commons_p"     => "El proyecto usa licencias que administran el copyright de manera más abierta. Esto abre nuevas líneas de negocio, y amplía masivamente el alcance de la distribución.",
  "dict_com_crowdfunding_p"         => "El Cosmonauta ha sido uno de los proyectos más exitoso del mundo en el uso del crowdfunding. Más de 400.000€ conseguidos gracias a 4.500 productores.",
  "dict_com_disruptive_team_p"      => "Riot Cinema y el equipo de \"El Cosmonauta\", entre los más jóvenes de la industria del cine español, han trabajado más de tres años y medio comprometiéndose al máximo.",
  "dict_com_download"               => "DESCARGAR",
  "dict_com_eastern_eggs"           => "Detrás de las cámaras",
  "dict_com_facebook"								=> "Facebook",
  "dict_com_film_universe"					=> "FILM UNIVERSE",
  "dict_com_foo_about"							=> "El proyecto",
  "dict_com_foo_blog"               => "Blog",
  "dict_com_foo_contact"						=> "Contacto",
  "dict_com_foo_behind"						  => "Tras las cámaras",
  "dict_com_foo_demand"							=> "Solicitar un evento",
  "dict_com_foo_downloads"          => "Descargas",
  "dict_com_foo_film_universe"			=> "Film universe",
  "dict_com_foo_find"								=> "Encuentra una proyección",
  "dict_com_foo_go_to_the_web_in"   => "English website here",
  "dict_com_foo_its_special"        => "Es especial",
  "dict_com_foo_k_program"					=> "K-Program",
  "dict_com_foo_nayik"              => "Nayik",
  "dict_com_foo_newsletter"					=> "Newsletter",
  "dict_com_foo_organize"						=> "Organizar una proyección",
  "dict_com_foo_panorama"						=> "Panorama",
  "dict_com_foo_plan"								=> "El Plan",
  "dict_com_foo_press"							=> "Prensa",
  "dict_com_foo_scripts"						=> "Guiones",
  "dict_com_foo_shop"								=> "Tienda",
  "dict_com_foo_team"								=> "El equipo",
  "dict_com_foo_the_experience"			=> "LIVE EXPERIENCE",
  "dict_com_foo_the_film"						=> "LA PELÍCULA",
  "dict_com_foo_the_project"        => "El proyecto",
  "dict_com_foo_timeline"						=> "Línea temporal",
  "dict_com_foo_trailer"            => "Trailer",
  "dict_com_foo_trailer_and_web"    => "El tráiler y la web están licenciadas bajo Creative Commons Atribución Compartir Igual No Comercial 3.0 Unported",
  "dict_com_foo_transmedia"					=> "Transmedia",
  "dict_com_foo_remix"							=> "REMIX",
  "dict_com_foo_riot"								=> "El Cosmonauta es un proyecto de Riot Cinema Collective",
  "dict_com_foo_submit"							=> "Envía tu remix",
  "dict_com_foo_submissions"				=> "Ver remixes",
  "dict_com_foo_watch_it"						=> "Ver ahora",
  "dict_com_foo_website_2012"       => "Website 2012",
  "dict_com_foo_with_collaboration" => "CON LA COLABORACIÓN DEL",
  "dict_com_hummingbird_series"     => "The hummingbird",
  "dict_com_k_pass"                 => "K-PASS",
  "dict_com_latest_blog"						=> "Lo último en el blog",
  "dict_com_licenses"     					=> "LICENCIAS",
  "dict_com_live_experience"				=> "LIVE EXPERIENCE",
  "dict_com_materials"              => "MATERIALES",
  "dict_com_nayik"									=> "Nayik",
  "dict_com_ope_error"              => "Ocurrió un error al realizar la operación",
  "dict_com_ope_success"            => "Operation realizada con éxito",
  "dict_com_read_more"							=> "Leer más",
  "dict_com_secret_newsletter"      => "Nuestro newsletter secreto",
  "dict_com_sign_in"                => "ACCEDE",
  "dict_com_shop"    	              => "TIENDA",
  "dict_com_the_book"               => "El libro",
  "dict_com_the_cosmonaut"          => "El Cosmonauta",
  "dict_com_thecosmonaut"           => "elcosmonauta",
  "dict_com_timeline"               => "LINEA DE TIEMPO",
  "dict_com_title"                  => "El Cosmonauta",
  "dict_com_terms_of_service"     	=> "CONDICIONES DE USO",
  "dict_com_transmedia_episodes"    => "Episodios Transmedia",
  "dict_com_twitter"								=> "Twitter",
  "dict_com_your_account"           => "Tu cuenta",

  /** ABOUT */
  "dict_abo_4_years_working"        => "4 años trabajando en un proyecto increible",
  "dict_abo_behind_scenes"					=> "Tras las cámaras",
  "dict_abo_behind_p1"              => "\"El Cosmonauta\" ha sido un viaje largo y difícil, como un romance épico. Y lleno de valiosas lecciones.",
  "dict_abo_behind_p2"              => "Viaja en el tiempo con nosotros desde la primera vez que hablamos de cosmonautas al estreno cuatro años más tarde.",
  "dict_abo_disruptive_team"        => "UN EQUIPO DISRUPTIVO",
  "dict_abo_download_photo"         => "Descargar fotogramas del film",
  "dict_abo_download_plan"          => "Descarga The Plan",
  "dict_abo_download_press"         => "Descarga el kit completo",
  "dict_abo_for_journalist"         => "Periodistas, bloggers y medios: todo lo que necesitás saber sobre el proyecto está aquí. Fotografías incluidas. Y bajo Creative Commons, para que las puedas usar donde quiras.",
  "dict_abo_impossible"       			=> "La idea imposible",
  "dict_abo_impossible_p1"       		=> "Tiempo atrás quisimos hacer una película y, en el camino, reinventar la forma en que las películas se financiaban, producían y distribuían. Buscar nuestro propio camino e involucrar al público.",
  "dict_abo_impossible_p2"       		=> "Nos llamaron locos. Dijeron que era imposible. Que no era realista y que jamás funcionaría.",
  "dict_abo_impossible_p3"       		=> "No les creímos.",
  "dict_abo_learn_more"             => "Ver video",
  "dict_abo_meet_all_the_people"    => "CONOCE AL RESTO DEL EQUIPO",
  "dict_abo_more_than_4500"         => "MÁS DE 4.500 PRODUCTORES",
  "dict_abo_meet_the_team"          => "Conoce al equipo",
  "dict_abo_meet_the_team_p"        => "Conoce al equipo de Riot Cinema y al resto de la gente involucrada en el proyecto",
  "dict_abo_or_check_our_special"   => "Agradecimientos especiales",
  "dict_abo_press_area"             => "Área de prensa",
  "dict_abo_team_bruno_1"           => "Director de la segunda unidad",
  "dict_abo_team_bruno_2"           => "Productor ejecutivo",
  "dict_abo_team_carola"            => "Productora ejecutiva",
  "dict_abo_team_nico_1"            => "Director y guionista",
  "dict_abo_team_nico_2"            => "Productor ejecutivo",
  "dict_abo_timeline"            		=> "Línea de tiempo",
  "dict_abo_three_principles"       => "Los tres pilares",
  "dict_abo_under_creative_commons" => "BAJO CREATIVE COMMONS",
  "dict_abo_with_the_help_of_1"     => "Con la ayuda de cientos de profesionales y el apoyo de más de 4.500 productores, ",
  "dict_abo_with_the_help_of_2"     => "\"El Cosmonauta\" es al fin una realidad. Más información sobre el proyecto",
  "dict_abo_with_the_help_of_3"     => "y el equipo detrás de él.",

  /** BEHIND THE SCENES */
  "dict_beh_bronking_of"			=> "Bronking of",
  "dict_beh_bronking_of_p"		=> "El cine es como Atila el Huno. Por donde pasa, no vuelve a crecer la hierba. Próximamente.",
  "dict_beh_hummingbird"			=> "The Hummingbird",
  "dict_beh_hummingbird_p1"		=> "La historia de \"El Cosmonauta\" se basa en lo que creíamos una \"leyenda negra\".",
  "dict_beh_hummingbird_p2"		=> "Tal vez no era tan leyenda.",
  "dict_beh_eastern_p"        => "Descartes, tomas falsas y perlas \"detrás de las cámaras\". Sólo para cosmonautas con K-Pass.",
  "dict_beh_i_hear_voices"    => "I HEAR VOICES FROM SPACE",
  "dict_beh_i_hear_voices_p"  => "En FK Digital Records se atrevieron a poner banda sonora al guión. Puedes oirlos en los webisodios.",
  "dict_beh_its_been"         => "Ha sido un viaje increible.",
  "dict_beh_original"         => "BANDA SONORA",
  "dict_beh_original_p"       => "La banda sonora del montaje original. Con Joan Valent como principal compositor.",
  "dict_beh_revive"           => "Revivelo con nosotros.",
  "dict_beh_soundtracks"      => "Bandas sonoras",
  "dict_beh_transmedia"       => "SESIONES TRANSMEDIA",
  "dict_beh_transmedia_p"     => "Otros 23 increibles temas. Muchos utilizados en webisodios o escenas eliminadas.",
  "dict_beh_video_diaries"    => "Videodiarios",

  /** CARTO DB */
	"dict_car_all_screenings"         => "VER TODAS LAS PROYECCIONES",
  "dict_car_cartodb_1"            	=> " proyecciones en ",
  "dict_car_cartodb_2"            	=> " países.",
  "dict_car_cartodb_3"            	=> " país.",
  "dict_car_data_city"							=> "Ciudad",
  "dict_car_data_date"							=> "Fecha",
  "dict_car_data_descriptor"				=> "Evento",
  "dict_car_data_tickets"						=> "Entradas",
  "dict_car_every_show"							=> "Cada vez que se proyecta \"El Cosmonauta\" es diferente: material extra, presencia del equipo, fiesta posterior… encuentra la proyección más cercana, solicítala u organízala tú mismo.",
  "dict_car_explore"								=> "EXPLORA EL MAPA",
  "dict_car_find_a_projection"			=> "Encuentra una proyección u organízala tú mismo para vivir toda la experience de El Cosmonauta.",
  "dict_car_offline_experience"			=> "Vive la experience offline",
  
  /** DASHBOARD */
  "dict_das_are_you_sure"           => "¿Estas seguro?",
  "dict_das_delete_account"         => "Eliminar tu cuenta",
  "dict_das_deleted_account"        => "Tu cuenta ha sido borrada con éxito",
  "dict_das_deleted_account_error"  => "Ocurrió un error al borrar tu cuenta",
  "dict_das_deleting_account"       => "Tu cuenta está siendo borrada ...",
  "dict_das_err_format_email"       => "Formato de e-mail incorrecto",
  "dict_das_err_required_firstname" => "El nombre es obligatorio",
  "dict_das_err_required_lastname"  => "El apellido es obligatorio",
  "dict_das_err_required_email"     => "El e-mail es obligatorio",
  "dict_das_its_great_to_have_you"  => "Es genial tenerte hoy con nosotros.",
  "dict_das_looks_like_you"         => "Parece que aún tienes bastante por descubrir",
  "dict_das_looks_like_you_still"   => "Parece que aún tienes cosas por descubrir",
  "dict_das_looks_like_experienced" => "¡Eres ya un cosmonauta experimentado!",
  "dict_das_this_will_completely"   => "Esto eliminará tu cuenta de manera permanente.",
  "dict_das_this_will_update"       => "Esta operación actualizará tu perfil de usuario",
  "dict_das_save_changes"           => "GUARDAR",
  "dict_das_update_account"         => "Actualiza tu cuenta",
  "dict_das_updated_account"        => "Tu cuenta ha sido actualizada con éxito",
  "dict_das_updated_account_error"  => "Ocurrió un error al actualizar tu cuenta",
  "dict_das_updating_account"       => "Tu cuenta ha sido actualizada ...",
  "dict_das_welcome_back"           => "Bienvenido a bordo, Cosmonauta",
  "dict_das_yes_im_sure"            => "ESTOY SEGURO",
  "dict_das_your_account"           => "Datos de tu cuenta",
  "dict_das_your_email"             => "Tu e-mail",
  "dict_das_your_code"              => "Tu código cosmonauta",
  "dict_das_your_name"              => "Tu nombre",
  "dict_das_your_surname"           => "Tus apellidos",

  /** EVENTS */
	"dict_eve_browse"									=> "Buscar por fecha",
	"dict_eve_buy"										=> "Comprar tickets",
	"dict_eve_city"										=> "CIUDAD",
	"dict_eve_date"										=> "FECHA",
	"dict_eve_more"										=> "VER MÁS",
	"dict_eve_no_tickets"							=> "Agotadas",
	"dict_eve_venue"									=> "LUGAR",

  /** HOME */
  "dict_hom_32_webisodes"           => "32 episodios web, un libro, el Bronking of, un mockumentary, toneladas de videos \"detrás de las cámaras\" y un acceso exclusivo a nuestro newsletter secreto. Cómpralo por sólo 5€ o consíguelo gratis comprando cualquier cosa en la tienda.",
  "dict_hom_a_film_32_web"          => "32 webisodios, un libro y un increible viaje de cuatro años preparando el proyecto que ahora puedes ver.",
  "dict_hom_a_film_made_by"         => "A film made by more than ",
  "dict_hom_countdown_1"            => "GRATIS ONLINE EN ",
  "dict_hom_countdown_2"            => " DÍAS",
  "dict_hom_creative_commons"       => "CREATIVE COMMONS",
  "dict_hom_crowdfunding"           => "CROWDFUNDING",
  "dict_hom_disruptive_team"        => "UN EQUIPO DISRUPTIVO",
  "dict_hom_enjoy_a_new_way"        => "Una nueva forma de experimentar historias. Sumérgete en el universo transmedia de \"El Cosmonauta\".",
  "dict_hom_get_your_k_pass"        => "Toda la experiencia con tu K-Pass",
  "dict_hom_how_has_it_be_done"     => "Cómo se ha hecho",
  "dict_hom_go_to_remix"            => "IR A REMIX",
  "dict_hom_learn_about_one"        => "Toda leyenda tiene un origen. El Cosmonauta ha sido la mayor aventura de nuestras vidas.",
  "dict_hom_more"        						=> "SABER MÁS",
  "dict_hom_much_more_than"         => "Mucho más que una película",
  "dict_hom_producers_list"         => "LISTA DE PRODUCTORES",
  "dict_hom_stats_get_lost_1"       => "Stas se pierde en el espacio. Cuando regresa, se encuentra con la Tierra",
  "dict_hom_stats_get_lost_2"       => "completamente vacía. Yulia y Andrei le esperan mientras su mundo se derrumba.",
  "dict_hom_stats_get_lost_3"       => "¿Hasta dónde llegarías por amor?",
  "dict_hom_watch_it_for_free"      => "Ver gratis online",

  /** K-PASS */
  "dict_kpa_32_webisodes_1"         => "32 webisodios, un libro, un falso documental, un montón de vídeos \"tras las cámaras\" y el acceso exclusivo a nuestro boletín secreto. Cómparlo ",
  "dict_kpa_32_webisodes_2"         => "sólo por 5€",
  "dict_kpa_32_webisodes_3"         => "o llévatelo gratis con la compra de cualquier otro ítem de la tienda.",
  "dict_kpa_become_part"            => "Conviértete en parte del Programa K",
  "dict_kpa_buy_yours"              => "Compra el tuyo",
  "dict_kpa_buy_your_k_pass"        => "COMPRA TU K-PASS",
  "dict_kpa_or_get_it_for_free"     => "O consíguelo gratis con cualquier ítem de la tienda",
  "dict_kpa_still"                  => "¿Aún no lo tienes?",
  "dict_kpa_unlock_more_than"       => "Desbloquea más de 60 contenidos exclusivos",

  /** LOGIN */
  "dict_log_are_you"                => "¿ERES COSMONAUTA?",
  "dict_log_forgot"                 => "Necesito una contraseña",
  "dict_log_insert_your"            => "INTRODUCE TUS CREDENCIALES",
  "dict_log_err"                    => "Datos de acceso incorrectos",
  "dict_log_err_format_login"       => "E-mail no válido",
  "dict_log_err_required_login"     => "El e-mail es obligatorio",
  "dict_log_err_required_password"  => "La contraseña es obligatoria",
  "dict_log_err_missing"            => "El e-mail y contrasena son obligatorios",
  "dict_log_sign_in"                => "ACCEDE",
  "dict_log_your_email"             => "Tu e-mail",
  "dict_log_your_password"          => "Tu password",
  "dict_log_what_is_this"           => "¿Qué es esto?",

  /** MAIL */
  "dict_mai_header_thankyou"        => "[ CosmonautExperience.com ] ¡Gracias!",
  "dict_mai_header_text_1"          => "¡Gracias por tu donación!",
  "dict_mai_header_text_2"          => "Tu cuenta ha sido creada y puedes conseguir tu contraseña en el siguiente enlace con tu dirección de e-mail: ",

  /** MOVIE */
	"dict_mov_average"								=> "La donación media es de ",
	"dict_mov_back_to_website"				=> "Volver a la web cosmonautexperience.com",
	"dict_mov_enjoying_1"							=> "¿Te gusta la película? \"El Cosmonauta\" es un",
	"dict_mov_enjoying_2"							=> "esfuerzo de cuatro años,",
	"dict_mov_enjoying_3"							=> "de fans y creadores ",
	"dict_mov_enjoying_4"							=> "juntos. Recuerda que puedes ayudarnos ...",
	"dict_mov_if_you_pay_1"						=> "Si pagas más de 5€ recibirás gratis tu ",
	"dict_mov_go_to_beginning"				=> "IR AL PRINCIPIO",
	"dict_mov_k_pass"									=> "K-Pass",
	"dict_mov_or"											=> "o",
	"dict_mov_or_sharing"							=> "O compartiendo el enlace con tus amigos.",
	"dict_mov_pay_with_paypal"				=> "Pagar con Paypal",
	"dict_mov_paying_what_you_want"		=> "Pagando por ella lo que quieras",
	"dict_mov_share"									=> "Compártela y vela gratis",
	"dict_mov_share_facebook"					=> "COMPARTE EN FACEBOOK",
	"dict_mov_share_twitter"					=> "COMPARTE EN TWITTER",
	"dict_mov_the_cosmonaut"					=> "EL COSMONAUTA",
	"dict_mov_watch_movie"						=> "VER LA PELÍCULA",
	"dict_mov_watch_the_movie"				=> "Ver la película pagando lo que tú quieras",
	"dict_mov_we_believe"							=> "Creemos en las buenas relaciones entre fans y creadores.",
	"dict_mov_we_can_only_1"					=> "Sólo podemos hacer películas con tu ayuda, pero ",
	"dict_mov_we_can_only_2"					=> "queremos que elijas",

	/** NAYIK */
  "dict_nay_ago_1"                  => "HACE",
  "dict_nay_ago_2"                  => "DÍAS",
  "dict_nay_ago_3"                  => "",
	"dict_nay_says"						        => "dice",
  "dict_nay_story_alive"            => "La historia está viva, y está en Nayik.",

  /** REMIX */
  "dict_rem_a_film_by"              => "Un cortometraje de",
  "dict_rem_attribution"            => "ATRIBUCIÓN",
  "dict_rem_attribution_p1"         => "No distribuyas el contenido de",
  "dict_rem_attribution_p2"         => "\"El Cosmonauta\" sin acreditarnos",
  "dict_rem_attribution_p3"         => "como autores.",
  "dict_rem_attribution_p4"         => "Aquí tienes sugerencias de ",
  "dict_rem_attribution_p5"         => "cómo hacerlo.",
  "dict_rem_commercial"             => "NO COMERCIAL",
  "dict_rem_commercial_p1"          => "Los usos comerciales no están",
  "dict_rem_commercial_p2"          => "permitidos sin nuestro",
  "dict_rem_commercial_p3"          => "consentimiento previo.",
  "dict_rem_derivatives"            => "SIN DERIVADOS",
  "dict_rem_derivatives_p1"         => "Materiales que no puedes alterar o",
  "dict_rem_derivatives_p2"         => "con los que no puedes hacer",
  "dict_rem_derivatives_p3"         => "obras nuevas.",
  "dict_rem_download_adapt"         => "Adapta nuestra web ",
  "dict_rem_download_adapt_2"       => "a tu proyecto",
  "dict_rem_download_direct"        => "Descarga directa.",
  "dict_rem_download_direct_2"      => "clips por separado",
  "dict_rem_download_guide"         => "Guía de material",
  "dict_rem_download_guide_2"       => "imprescindible",
  "dict_rem_download_materials"     => "Descárgate los materiales de la película (próximamente)",
  "dict_rem_download_torrent"       => "Descarga el Torrent",
  "dict_rem_download_torrent_2"     => "todos los clips",
  "dict_rem_exceptions"             => "contadas excepciones",
  "dict_rem_help_of"                => "Esta sección no hubiera sido posible sin la inestimable ayuda de...",
  "dict_rem_license"                => "MANTENER LA LICENCIA",
  "dict_rem_license_p1"             => "Si alteras o transformas la obra, o",
  "dict_rem_license_p2"             => "generas una obra derivada, sólo",
  "dict_rem_license_p3"             => "puedes distribuirla bajo una licencia",
  "dict_rem_license_p4"             => "idéntica a la licencia original.",
  "dict_rem_other_conditions"       => "Y estas son otras condiciones que podrías encontrar",
  "dict_rem_permissions"            => "PERMISOS ADICIONALES",
  "dict_rem_permissions_p1"         => "Si ves este icono es que la licencia",
  "dict_rem_permissions_p2"         => "no aplica a todo el contenido.",
  "dict_rem_permissions_p3"         => "Usa la ",
  "dict_rem_permissions_p4"         => "Guía de Licencias.",
  "dict_rem_remix"                  => "REMEZCLAR",
  "dict_rem_remix_p1"               => "Puedes alterarlo, crear nuevas",
  "dict_rem_remix_p2"               => "versiones o utilizarlo en tus",
  "dict_rem_remix_p3"               => "propias obras.",
  "dict_rem_remix_movie"            => "Remezcla la película",
  "dict_rem_remix_the_way"          => "Nuestra película está licenciada con Creative Commons. Puedes distribuirla libremente siempre que no te lucres directa ni indirectamente con ella. También puedes remontarla como a ti te gustaría o elegir tomas diferentes a las usadas por nuestros montadores. Y utilizar nuestras imágenes HD de cosmonautas, paisajes y lugares desolados en tu proyecto personal. El concepto es simple: si no ganas, nosotros tampoco. Si obtienes beneficio, lo compartimos.",
  "dict_rem_share"                  => "COMPARTIR",
  "dict_rem_share_p1"               => "Puedes compartirlo, copiarlo, ",
  "dict_rem_share_p2"               => "distribuirlo y exhibirlo.",
  "dict_rem_this_is_what_you"       => "Esto es lo que puedes hacer ...",
  "dict_rem_upload"                 => "SUBE TU VIDEO",
  "dict_rem_upload_p1"              => "¿Tienes algún remix bajo la manga? ¡Únete a nuestro grupo en Vimeo y",
  "dict_rem_upload_p2"              => "añádelo para compartirlo con nosotros!",
  "dict_rem_week_remix_1"           => "EL REMIX DE LA SEMANA EN ",
  "dict_rem_week_remix_2"           => "\"EL COSMONAUTA REMIX\"",
  "dict_rem_what_you_respect"       => "Esto es lo que debes respetar",
  "dict_rem_with_all_content"       => "... con todo el contenido de \"El Cosmonauta\" (excepto",

  /** THANKS */
  "dict_tha_account"                => "TU CUENTA HA SIDO CREADA.",
  "dict_tha_p1"                     => "Puedes solicitar la contraseña de tu K-Pass",
  "dict_tha_p2"                     => "o",
  "dict_tha_p3"                     => "empezar a ver la película ya.",
  "dict_tha_thank_you"              => "¡GRACIAS!",
  "dict_tha_request_password"       => "PEDIR CONTRASEÑA",
  "dict_tha_watch_it_now"           => "VER LA PELÍCULA",

  /** TIMELINE */
  "dict_tim_2008end_p"              => "Convertimos el cortometraje \"El Viaje del Cosmonauta\" en el largometraje \"El Cosmonauta\".",
  "dict_tim_2008end"                => "FINALES DE 2008",
  "dict_tim_2009begin_p"            => "La lectura del libro \"Poética para Cosmonautas\" termina de dar forma al esqueleto de la futura película.",
  "dict_tim_2009begin"              => "PRINCIPIOS DE 2009",
  "dict_tim_20090118"               => "18, ENE, 2009",
  "dict_tim_20090118_p"             => "Conseguimos dos trajes de entrenamiento de cosmonautas, que nos acompañarán durante toda la aventura, y con los que rodaremos dos años después.",
  "dict_tim_20090124"               => "24, ENE, 2009",
  "dict_tim_20090124_p"             => "Decidimos financiar \"El Cosmonauta\" mediante Crowdfunding.",
  "dict_tim_20090216"               => "16, FEB, 2009",
  "dict_tim_20090216_p"             => "Conocemos a Henry Pierrot, el autor de \"Poética para Cosmonautas\", que se une al proyecto.",
  "dict_tim_20090320"               => "20, MAR, 2009",
  "dict_tim_20090320_p"             => "Viajamos a Star City (Moscú) la impresionante localización que nos obsesionará el resto del proyecto.",
  "dict_tim_20090415"               => "15, ABR, 2009",
  "dict_tim_20090415_p"             => "El prestigioso estudio Vostok apuesta por el proyecto y decide hacernos la página web.",
  "dict_tim_20090422"               => "22, ABR, 2009",
  "dict_tim_20090422_p"             => "Laszlo Kovacs crea el emblema de la película: el Colibrí.",
  "dict_tim_20090424"               => "24, ABR, 2009",
  "dict_tim_20090424_p"             => "Presentamos el proyecto en Medialab (Madrid) y en una improvisada subasta ganamos nuestro primer productor.",
  "dict_tim_20090511"               => "11, MAY, 2009",
  "dict_tim_20090511_p"             => "Lanzamos la página web, que te permite hacerte productor de la película.",
  "dict_tim_20090623"               => "23, JUN, 2009",
  "dict_tim_20090623_p"             => "Eduard Artemyev, el compositor de nuestro admirado Andrey Trakovsky, nos cede la música que compuso para su película \"Solaris\".",
  "dict_tim_20090627"               => "27, JUN, 2009",
  "dict_tim_20090627_p"             => "El País nos llama \"el proyecto más estimulante del cine español\" a página completa en su suplemento.",
  "dict_tim_20090630"               => "30, JUN, 2009",
  "dict_tim_20090630_p"             => "Festival \"Cosmonauts\": grandes del indie tocan en beneficio de la película.",
  "dict_tim_20090712"               => "12, JUL, 2009",
  "dict_tim_20090712_p"             => "Primer inversor.",
  "dict_tim_20090820"               => "20, AGO, 2009",
  "dict_tim_20090820_p"             => "En 10 minutos financiamos la reedición de \"Poética para Cosmonautas\", el libro que es uno de los orígenes de la película.",
  "dict_tim_20091014"               => "14, OCT, 2009",
  "dict_tim_20091014_p"             => "Asistimos a Power to The Pixel en UK. La idea de Transmedia nos transforma profundamente.",
  "dict_tim_20091015_p"             => "Llegamos a 1000 productores. Hacemos una fiesta para celebrarlo. No cabemos en el local.",
  "dict_tim_20091015"               => "15, OCT, 2009",
  "dict_tim_20100121"               => "21, ENE, 2010",
  "dict_tim_20100121_p"             => "Teaser de la película. Un éxito instantáneo. Stas (aún llamado \"Stan\") es nuestro gran amigo y tremendo actor Carlos Martínez Abarca.",
  "dict_tim_20100211"               => "11, FEB, 2010",
  "dict_tim_20100211_p"             => "Nicolás escribe el guión del largometraje. Decidimos hacer la película, después de mucho pensar, en inglés.",
  "dict_tim_20100407"               => "7, ABR, 2010",
  "dict_tim_20100407_p"             => "WIRED nos cita como \"uno de los mayores éxitos de la creatividad colectiva\".",
  "dict_tim_20100503"               => "3, MAY, 2010",
  "dict_tim_20100503_p"             => "Teaser Remix Experience: más de 100 remezclas del Teaser Trailer. Algunas son increíbles. Nos reafirma la idea de hacer lo mismo con toda la película.",
  "dict_tim_20100602"               => "2, JUN, 2010",
  "dict_tim_20100602_p"             => "Publicamos nuestra estrategia (The Plan), el presupuesto y plan financiero y el primer borrador del guión.",
  "dict_tim_20100620"               => "20, JUN, 2010",
  "dict_tim_20100620_p"             => "Nueva web, también del estudio Vostok. Diseño rompedor.",
  "dict_tim_20101006"               => "6, OCT, 2010",
  "dict_tim_20101006_p"             => "Nos seleccionan en el Latin American Film Training y viajamos a Hollywood para aprender cómo funciona.",
  "dict_tim_20101123"               => "23, NOV, 2010",
  "dict_tim_20101123_p"             => "Comienza la pre-producción.",
  "dict_tim_20110317"               => "17, MAR, 2011",
  "dict_tim_20110317_p"             => "Publicamos el segundo teaser. Siguen siendo imágenes rodadas en Madrid.",
  "dict_tim_20110328"               => "28, MAR, 2011",
  "dict_tim_20110328_p"             => "Desvelamos el rostro de nuestros tres actores principales: Tres caras del teatro y la Tv británica interpretarán a Andrei, Yulia y Stas.",
  "dict_tim_20110401"               => "1, ABR, 2011",
  "dict_tim_20110401_p"             => "Viajamos a Moscú para no perder las primeras nieves. Publicamos las imágenes que grabamos. Gustan mucho.",
  "dict_tim_20110422"               => "22, ABR, 2011",
  "dict_tim_20110422_p"             => "3000 productores.",
  "dict_tim_20110505"               => "2, MAY, 2011",
  "dict_tim_20110505_p"             => "Entra un prometedor co-productor ruso a producir con nosotros.",
  "dict_tim_20110506"               => "6, MAY, 2011",
  "dict_tim_20110506_p"             => "Cerramos unas alucinantes localizaciones en Letonia mientras acabamos los ensayos con los actores.",
  "dict_tim_20110525"               => "25, MAY, 2011",
  "dict_tim_20110525_p"             => "Se cae nuestro inversor ruso. Lanzamos la campaña Save The Cosmonaut para conseguir al menos 40.000€ en un mes. Conseguimos 130.000€ en tres días.",
  "dict_tim_20110604"               => "4, JUN, 2011",
  "dict_tim_20110604_p"             => "Comienza el rodaje.",
  "dict_tim_20110627"               => "27, JUN, 2011",
  "dict_tim_20110627_p"             => "Comenzamos a emitir el rodaje en directo.",
  "dict_tim_20110715"               => "15, JUL, 2011",
  "dict_tim_20110715_p"             => "Acabamos el rodaje.",
  "dict_tim_20111031"               => "31, OCT, 2011",
  "dict_tim_20111031_p"             => "Presentamos The Plan 2, el nuevo \"recap\" de nuestra estrategia.",
  "dict_tim_20111104"               => "4, NOV, 2011",
  "dict_tim_20111104_p"             => "Primer trailer con imágenes de la película.",
  "dict_tim_20120224"               => "24, FEB, 2012",
  "dict_tim_20120224_p"             => "Etapa final de montaje.",
  "dict_tim_20120529"               => "25, MAY, 2012",
  "dict_tim_20120529_p"             => "Acabamos el montaje, casi un año después de rodar la película. Tres bandas sonoras. 80 minutos de largometraje. 80 de transmedia. Mucho más de Easter Eggs y documental.",
  "dict_tim_20120715"               => "15, AGO, 2012",
  "dict_tim_20120715_p"             => "Se unen Entropy (FX), Pecera Estudio (Sonido) y Joan Valent (Banda Sonora) gracias a la aportación de 80.000€ de Pepephone.",
  "dict_tim_20121023"               => "23, OCT, 2012",
  "dict_tim_20121023_p"             => "Dos años después de reeditarla, se agota Poética para Cosmonautas.",
  "dict_tim_20121123"               => "23, NOV, 2012",
  "dict_tim_20121123_p"             => "Al fin cerramos nuestra estrategia final: publicamos \"The Plan 3\".",
  "dict_tim_20121013"               => "13, OCT, 2012",
  "dict_tim_20121013_p"             => "Vení comienza a hacer los increíbles créditos finales de la película.",
  "dict_tim_20130214"               => "14, FEB, 2013",
  "dict_tim_20130214_p"             => "Lanzamiento del tráiler final, anuncio de la fecha de estreno (18 de Mayo) y apertura del sistema \"pide un estreno en tu ciudad\". Las tres son un éxito rotundo.",
  "dict_tim_this_has_been"          => "Ha sido un viaje increíble.",
  "dict_tim_read_more"              => "Leer más",
  "dict_tim_revive"                 => "Revívelo con nosotros.",

  /** TRAILER */
  "dict_tra_32_webisodes"           => "32 episodios web, un libro, el Bronking Of, un mockumentary, toneladas de videos \"detrás de las cámaras\" y acceso exclusivo a nuestro newsletter secreto. Cómpralo por sólo 5€ o consíguelo gratis comprando cualquier otra cosa en la tienda.",
  "dict_tra_also_in_theaters"       => "También en cines",
  "dict_tra_beyond"                 => "Va más allá del copyright",
  "dict_tra_check_out"              => "Comprueba las razones que han hecho de este proyecto algo que cambiará la manera en que entendemos el cine.",
  "dict_tra_cosmonaut_experience"   => "La experiencia \"El Cosmonauta\" es mucho mejor cuando la compartes con tus amigos. Encuentra una proyección cercana, solicítala u organiza una tú mismo.",
  "dict_tra_demand_a_show"          => "SOLICITAR UNA PROYECCIÓN",
  "dict_tra_demand_your_offline"    => "Solicita un estreno en tu ciudad u organízalo tu mismo, te ayudaremos.",
  "dict_tra_download_material"      => "Copia, remezcla y distribuye la película como quieras.",
  "dict_tra_get_your_k_pass"        => "Toda la experiencia con tu K­-Pass",
  "dict_tra_go_to_website"          => "Ir a la antigua web",
  "dict_tra_has_been_made"          => "El Cosmonauta ha sido posible gracias a más de 4.500 fans e inversores.",
  "dict_tra_in_all_your"            => "En todas tus pantallas",
  "dict_tra_its_an_experience"      => "Es una experiencia",
  "dict_tra_its_crowdfunded"        => "Es crowdfunding",
  "dict_tra_its_free"               => "Es gratis",
  "dict_tra_or"                     => "o",
  "dict_tra_organize_it"            => "ORGANÍZALA",
  "dict_tra_planned_shows"          => "Proyecciones planificadas",
  "dict_tra_premiere"               => "14 de Mayo de 2013",
  "dict_tra_cosmonaut_experience"		=> "La experiencia \"El Cosmonauta\" es mucho mejor cuando la compartes con tus amigos. Encuentra una proyección cercana, solicítala u organiza una tú mismo.",
  "dict_tra_theater_experience"     => "Experiencia en cines",
  "dict_tra_this_is_not"            => "No es sólo una película: 32 episodios adicionales, una experiencia en cine y mucho más.",
  "dict_tra_tugg"										=> "Proyecciones Tugg",
  "dict_tra_users_demanding"        => "Solicitudes de usuarios",
  "dict_tra_watch_it_for_free"      => "Puedes verla gratis o pagar por tu K-Pass, que te dará acceso a toda la experiencia.",
  "dict_tra_watch_the_trailer"      => "Ver el trailer",
  "dict_tra_we_have_a_plan"         => "Tenemos un plan",
  "dict_tra_we_love_transpar_1"     => "Nos gusta ser transparentes. Descarga ",
  "dict_tra_we_love_transpar_2"     => "aquí",
  "dict_tra_we_love_transpar_3"     => "toda nuestra estrategia.",
  "dict_tra_why_you_should"         => "¿Por qué no debes perdértela?",

  /** TRAILER / DEMAND EVENT */
  "dict_tra_dem_accept_tos"           => "He leído y acepto las ",
  "dict_tra_dem_alert_me"             => "Avisadme sólo cuando haya eventos en mi área",
  "dict_tra_dem_by_doing_this"        => "Si les ayudas, la organización puede regalarte merchandising o entradas.",
  "dict_tra_dem_cant_find"            => "¿No encuentras en evento cerca tuyo?",
  "dict_tra_dem_conf_demand_head"     => "HEMOS REGISTRADO TU PETICIÓN",
  "dict_tra_dem_conf_demand_p1"       => "Aparecerá en el mapa en unas horas.",
  "dict_tra_dem_conf_demand_p2"       => "¡Gracias!",
  "dict_tra_dem_close"                => "Cerrar",
  "dict_tra_dem_contact_info"         => "Sobre tí",
  "dict_tra_dem_demand_an_event"      => "Pide un evento",
  "dict_tra_dem_error_accept"         => "Debe aceptar las condiciones de uso",
  "dict_tra_dem_error_city"           => "Ops, el nombre de la ciudad es obligatorio",
  "dict_tra_dem_error_email"          => "Ops, parece que el email no es correcto",
  "dict_tra_dem_error_generic_demand" => "Estos datos ayudan mucho a los organizadores",
  "dict_tra_dem_error_locating_head"  => "Ops, hubo un problema localizando tu petición",
  "dict_tra_dem_error_locating_body"  => "Algo ha ido mal y no hemos podido ubicar tu peticíon en el mapa. Por favor, intentalo de nuevo o ponte en contacto con el webmaster si el problema continúa.",
  "dict_tra_dem_error_sendmail"       => "Ops, parece que no se ha podido enviar el formulario",
  "dict_tra_dem_error_type"           => "Ops, al menos debes seleccionar uno de los tipos",
  "dict_tra_dem_error_zip_code"       => "Ops, el código postal es obligatorio",
  "dict_tra_dem_experience"           => "Experience",
  "dict_tra_dem_home_screening"       => "Home screening",
  "dict_tra_dem_normal"               => "Normal",
  "dict_tra_dem_postal_code"          => "Tu código postal",
  "dict_tra_dem_prefered_event"       => "Evento preferido",
  "dict_tra_dem_really"               => "¿De verdad?",
  "dict_tra_dem_submit_proposal"      => "Enviar propuesta",
  "dict_tra_dem_terms_of_service"     => "Condiciones de uso",
  "dict_tra_dem_type"                 => "Tipo",
  "dict_tra_dem_yes_im_up"            => "Si, me gustaría ayudar a organizar un evento en mi ciudad.",
  "dict_tra_dem_you_can_select"       => "Puedes seleccionar uno o todos. Eso le dará a los organizadores idea de lo que quieres.",
  "dict_tra_dem_your_city"            => "Tu ciudad",
  "dict_tra_dem_your_email"           => "Tu email",
  "dict_tra_dem_wanna_help"           => "¿Quieres ayudar?",

  /** TRAILER / ORGANIZE */
  "dict_tra_org_35mm"                 => "35mm",
  "dict_tra_org_about_you"            => "SOBRE TÍ",
  "dict_tra_org_additional_contents"  => "Contenido adicional",
  "dict_tra_org_address"              => "Ciudad del evento",
  "dict_tra_org_after_party"          => "After party",
  "dict_tra_org_amateur_event"        => "SemiPro/Amateur",
  "dict_tra_org_complete_name"        => "Nombre completo",
  "dict_tra_org_conf_organize_head"   => "!Gracias",
  "dict_tra_org_conf_organize_p1"     => "Te contactaremos lo antes posible para cerrar todos los detalles de tu evento. En unos minutos. En unos minutos recibirás un resumen de este formulario.",
  "dict_tra_org_conf_organize_p2"     => "¡Qué ganas de llevar El Cosmonauta a ",
  "dict_tra_org_date"                 => "Fecha",
  "dict_tra_org_dcp"                  => "DCP",
  "dict_tra_org_dni"                  => "DNI / Valid iD",
  "dict_tra_org_dvd_bluray"           => "DVD",
  "dict_tra_org_describe_your_event"  => "Describe tu evento",
  "dict_tra_org_detailed_description" => "Danos detalles del evento que tienes en mente y del lugar donde lo harás.",
  "dict_tra_org_dont_be_afraid_1"     => "No te preocupes, necesitamos sólo una visión general de tu evento",
  "dict_tra_org_dont_be_afraid_2"     => "Antes de rellenar el formulario necesitamos que leas nuestra ",
  "dict_tra_org_email"                => "Email",
  "dict_tra_org_error_address"        => "Ops, la dirección postal es obligatoria",
  "dict_tra_org_error_date"           => "Ops, la fecha del evento es obligatoria",
  "dict_tra_org_error_descriptor"     => "Ops, la descripción del evento es obligatoria",
  "dict_tra_org_error_email"          => "Ops, el email no parece correcto",
  "dict_tra_org_error_format"         => "Ops, se debe seleccionar al menos un formato",
  "dict_tra_org_error_generic_org"    => "Si nos cuentas esto nos adaptaremos mejor a tí",
  "dict_tra_org_error_id"             => "Ops, el DNI es obligatorio",
  "dict_tra_org_error_lang"           => "Ops, se debe seleccionar al menos una opción de idioma",
  "dict_tra_org_error_name"           => "Ops, el nombre el obligatorio",  
  "dict_tra_org_error_phone"          => "Ops, el número de teléfono es obligatorio",
  "dict_tra_org_error_sendmail"       => "Ops, parece que no se ha podido enviar el formulario",
  "dict_tra_org_error_where"          => "Ops, al menos se debe seleccionar un tipo de evento",
  "dict_tra_org_expected_number"      => "Público esperado (aprox)",
  "dict_tra_org_extras"               => "EXTRAS",
  "dict_tra_org_final_cost"           => "PRECIO FINAL",
  "dict_tra_org_format"               => "Formato",
  "dict_tra_org_free"                 => "GRATIS",
  "dict_tra_org_language"             => "Idioma",
  "dict_tra_org_merchandising"        => "MERCHANDISING",
  "dict_tra_org_non_profit"           => "Sin Lucro",
  "dict_tra_org_organize_your_own"    => "Organiza tu propia experiencia",
  "dict_tra_org_phone"                => "Teléfono",
  "dict_tra_org_professional_event"   => "Profesional",
  "dict_tra_org_q_and_a"              => "Q & A",
  "dict_tra_org_screening_guide"      => "Screening guide",
  "dict_tra_org_snacks"               => "Snacks y otros",
  "dict_tra_org_streaming"            => "STREAMING",
  "dict_tra_org_submit"               => "Enviar",
  "dict_tra_org_tdb"                  => "(Veremos el precio luego)",
  "dict_tra_org_technical_stuff"      => "TÉCNICO",
  "dict_tra_org_vo"                   => "V.O.",
  "dict_tra_org_vo_english"           => "V.O. (English subts)",
  "dict_tra_org_vo_spanish"           => "V.O. (Subtit. Castellano)",
  "dict_tra_org_where"                => "Tipo",
  "dict_tra_org_your_event"           => "TU EVENTO",
  "dict_tra_org_your_features"        => "Añadidos",

  /** TWITTER  */
	"dict_twitter_hashtag"				 => "cosmonauta",
	"dict_twitter_text_eastern"		 => "Viendo los secretos de El Cosmonauta en sus EasternEggs",
	"dict_twitter_text_experience" => "Los ojos como platos con El Cosmonauta. Viendo el webisodio ",
	"dict_twitter_text_movie"			 => "Los ojos como platos con El Cosmonauta. #cosmonauta Cosmonauta GRATIS en ",
	"dict_twitter_text_videodiary" => "Viendo los videodiarios de El Cosmonauta: ¡haciendo historia!",

  /** UNIVERSE */
	"dict_uni_18_may"       					=> "Online gratis el 18 de Mayo",
  "dict_uni_alternate_ending"       => "Final alternativo",
  "dict_uni_coming_1"       				=> "Disponible el ",
  "dict_uni_coming_2"       				=> "de",
  "dict_uni_moon_warm_up"           => "MOON WRAP-UP",
  "dict_uni_moon_warm_up_p"         => "Los días antes de la partida las auroras boreales cubren el cielo...",
  "dict_uni_star_city_1"            => "Los rusos nunca llegaron a",
  "dict_uni_star_city_2"            => " la Luna pero... ¿y si lo intentaron",
  "dict_uni_star_city_3"            => " y nunca lo supimos?",
  "dict_uni_the_beginning"          => "EL PRINCIPIO",
  "dict_uni_the_beginning_p"        => "En 1957 entra en órbita el primer satélite artificial. Comenzaba una carrera salvaje entre dos países que ya luchaban una guerra secreta. La Tierra ya no era suficiente. El nuevo objetivo era conquistar el universo.",
  "dict_uni_the_book"               => "El libro",
  "dict_uni_the_cosmonaut"          => "THE COSMONAUT",
  "dict_uni_the_cosmonaut_p"        => "Una película que está cambiando la forma de relacionarse con el espectador. La pieza central de la experiencia cosmonáutica.",
  "dict_uni_the_good_old_days"      => "THE GOOD OLD DAYS",
  "dict_uni_the_good_old_days_p"    => "1967. Los recuerdos duran hasta nuestro último aliento. Cuando Stas y Andrei llegan a Star City conocen a Yulia, una técnico de comunicaciones que cambiará sus vidas para siempre.",
  "dict_uni_the_journey"            => "THE JOURNEY",
  "dict_uni_the_journey_p"          => "Tres días de viaje. Dieciséis mil toneladas de metal. Ocho mil kilómetros por hora...",
  "dict_uni_the_lost_cosmonauts"    => "THE LOST COSMONAUTS",
  "dict_uni_the_lost_cosmonauts_p"  => " ... los beeps se convierten en un ritmo. En un latido. Un latido humano. Unos días después, la Unión Soviética anunció que una nave se había desintegrado en el límite de la atmósfera. Una nave no tripulada, por supuesto ...",
  "dict_uni_the_moon_files"         => "THE MOON FILES",
  "dict_uni_the_moon_files_p"       => "El viaje llega a su fin. En estos diarios del vacío veremos atarse todos los cabos, encajarse las últimas piezas. Es el último viaje. Son los Moon Files.",
  "dict_uni_the_true_end"           => "EL VERDADERO FINAL",
  "dict_uni_v_o_i_d"                => "V-A-C-Í-O",
  "dict_uni_v_o_i_d_p_1"            => "Finalmente, el cosmonauta",
  "dict_uni_v_o_i_d_p_2"            => "regresa a La Tierra",
  "dict_uni_while_nasa"             => "Mientras los Estados Unidos fundaban la NASA para unificar su estrategia espacial… En la URSS, las cosas eran muy diferentes.",

  /** VIDEO */
  "dict_vid_anonimous"              => "Anónimo",
  "dict_vid_ask"                    => "Pregunta lo que quieras sobre este episodio...",
  "dict_vid_buy_it_for_just"        => "Cómpralo por sólo 5€ y desbloquéalo todo.",
  "dict_vid_comment"                => "Comentar",
  "dict_vid_comment_error"          => "Hubo un problema al publicar tu comentario.",
  "dict_vid_comment_error_logged"   => "Debes identificarte para poder comentar un video.",
  "dict_vid_comment_error_required" => "El comentario es obligatorio",
  "dict_vid_comment_success"        => "Comentario publicado con éxito.",
  "dict_vid_get_your_k_pass"        => "Consigue tu K-Pass",
  "dict_vid_more_info"              => "Más información",
  "dict_vid_or"                     => "o",
  "dict_vid_questions_about"        => "Preguntas sobre este capítulo",
  "dict_vid_sign_in"                => "Accede",
  "dict_vid_to_comment"             => "para comentar",
  "dict_vid_you_need_a_k_pass"      => "Necesitas un k-pass para ver esto."  
);